<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Osu.StablePlus.Performance.Engine/Osu.StablePlus.Performance.Engine.csproj" />
        <PackageReference Include="NUnit" Version="4.5.1" />
        <PackageReference Include="NUnitLite" Version="4.5.1" />
    </ItemGroup>
</Project>
